Add director
Lex4509/java-filmorate pull request #5
Opened 2022-12-05 20:01 UTC by Lex4509

Добавил функциональность согласно задаче Добавление режиссёров в фильмы

2022-12-05 21:47 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return jdbcTemplate.query(sql, this::mapRowToFilm, directorId);
Можем вынести мапперы в отдельный пакет, как это было у тебя сделано, чтобы не дублировать мапперы, когда они необходимы в каком-то другом Dao (просто мне пригодится такой функционал в таске, сразу сделаем, если возможно)

2022-12-05 21:48 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
>      private Film mapRowToFilm(ResultSet rs, int rowNum) throws SQLException {
Если перенесешь мапперы не забудь удалить их реализацию через методы

2022-12-05 21:53 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
>                  .map(this::setGenres)
Я забыл поправить это, если сможешь, то поменяй **map** на **peek**, кажется, он будет более уместным, т.к. мы не маппим один объект в другой, а просто меняем внутреннее состояние элемента.

2022-12-05 21:57 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        if (directorDao.findById(directorId)!=null) {
Если я не ошибаюсь, ты добавил exception с проверкой на null режиссеров, можно вместо этого **if** сразу проверить null с помощью exception -> **throwExceptionIfDirectorNotExists(directorDao.findById(directorId);** и избежав вложенности if

2022-12-05 22:02 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +            if (sortBy.equals("year"))
Возможно, с фигурными скобками всё таки было бы немного удобней читать код. Мне кажется однострочные ещё можно без скобок, но тут смотри сам)

2022-12-05 22:09 UTC, axoryl requested changes
Быстро ты)
Не понял только должен был ли я сразу approve сделать, вместо request changes, а то комменты в основном необязательные.

2022-12-06 10:17 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        System.out.println(jdbcTemplate.query(sql, this::mapRowToFilm, directorId));
Вот это ты забыл убрать

2022-12-06 11:19 UTC, Lex4509 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return jdbcTemplate.query(sql, this::mapRowToFilm, directorId);
Вынес

2022-12-06 11:20 UTC, Lex4509 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
>                  .map(this::setGenres)
Насколько это критично? это вызывает некоторые дополнительные изменения, может так оставим?

2022-12-06 11:20 UTC, Lex4509 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        if (directorDao.findById(directorId)!=null) {
сделал

2022-12-06 11:20 UTC, Lex4509 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +            if (sortBy.equals("year"))
Добавил скобки

2022-12-06 11:22 UTC, Lex4509 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        System.out.println(jdbcTemplate.query(sql, this::mapRowToFilm, directorId));
Убрал)

2022-12-06 11:22 UTC, Lex4509 commented
Изменения внес, посмотри пжл

2022-12-06 11:39 UTC, axoryl commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
>                  .map(this::setGenres)
@Lex4509 разве? Там вроде только где setGenres и setDirectors с map на peek сделать и всё, функционал не меняется, если я не ошибаюсь. Так оно не критично, могу в своей ветке уже изменить потом)

2022-12-06 11:45 UTC, axoryl approved these changes

2022-12-06 11:46 UTC, axoryl commented
Еле кнопку нашёл как с request changes на approve сделать) Осталось ещё 1 подтверждение

2022-12-06 12:45 UTC, SergeyAnosov approved these changes
Логирование нам вообще делать не надо?

2022-12-06 12:46 UTC, axoryl commented
Я думаю это по желанию больше

2022-12-06 12:54 UTC, merged